/** Select Statements for our tables**/

SELECT * FROM ACCOUNT_GROUP3;

SELECT * FROM CUSTOMERTBL_GROUP3;

SELECT * FROM LOGIN_GROUP3;

SELECT * FROM TRANSACTION_GROUP3;

/**Sequences created**/
CUSTOMERsequence_Group3
PASSWORDsequence_Group3

/**Scripts of tables**/

CREATE TABLE LOGIN_GROUP3
	(
	USERNAME  VARCHAR2 (50) NOT NULL,
	PASSWORD  VARCHAR2 (50) NOT NULL,
	LOGINTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USERNAME)
	)
	INSERT INTO LOGIN_GROUP3 values('M1349726ankita','ankita726')
	
	COMMIT
	
	CREATE TABLE AJA33CORE.CUSTOMERTBL_GROUP3
	(
	SSN_ID         NUMBER (9) NOT NULL,
	CUSTOMER_ID    NUMBER (9) NOT NULL,
	CUSTOMER_NAME  VARCHAR2 (20),
	AGE            NUMBER (3) NOT NULL,
	ADDRESS_LINE_1 VARCHAR2 (20),
	ADDRESS_LINE_2 VARCHAR2 (20),
	CITY           VARCHAR2 (225) CHECK (CITY IN ('MUMBAI','KOLKATA','PUNE','BANGALORE','MANGLORE','KOCHI','PATNA','GANDHINAGAR','DHANBAD','NEW DELHI','HYDERABAD','OLD DELHI')),
	STATE          VARCHAR2 (225) CHECK (STATE IN ('MUMBAI','West Bengal','BANGALORE','Tamil Nadu','Bihar','GUJARAT','DELHI','ANDRA PRADESH','KARNATAKA')),
	STATUS         VARCHAR2 (10) CHECK (status='Activated' OR status='Deactivated'),
	USERNAME       VARCHAR2 (50) NOT NULL,
	PRIMARY KEY (SSN_ID),
	UNIQUE (CUSTOMER_ID)
	)
	TABLESPACE AJA33CORE
	LOGGING
	NOCACHE
	STORAGE (BUFFER_POOL DEFAULT);


	CREATE SEQUENCE CUSTOMERsequence_Group3
	START WITH 12345654
	INCREMENT BY 1
	NOMINVALUE
	MAXVALUE 999999999
	NOCYCLE
	NOORDER
	CACHE 20;
	Select * FROM CUSTOMER_GROUP3
	DELETE FROM CUSTOMER_GROUP3
	
	CREATE SEQUENCE PASSWORDsequence_Group3
	START WITH 1023
	INCREMENT BY 1
	NOMINVALUE
	MAXVALUE 999999999
	NOCYCLE
	NOORDER
	CACHE 20;
	
CREATE SEQUENCE ACCOUNT_sequence_Group3
	START WITH 11117862
	INCREMENT BY 1
	NOMINVALUE
	MAXVALUE 999999999
	NOCYCLE
	NOORDER
	CACHE 20;

CREATE TABLE AJA33CORE.ACCOUNT_GROUP3
	(
	ACCOUNTID   NUMBER (9) NOT NULL,
	CUSTOMERID  NUMBER (9),
	ACCOUNTTYPE VARCHAR2 (50) CHECK (accounttype IN('Savings','Current')),
  	 BALANCE     NUMBER (7) CHECK (balance>0),
  	 CRDATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CRLASTDATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DURATION    NUMBER (20),
	STATUS      VARCHAR2 (20) CHECK (status IN('activate','deactivate')),
	LASTUPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY (ACCOUNTID),
	FOREIGN KEY (CUSTOMERID) REFERENCES AJA33CORE.CUSTOMERTBL_GROUP3 (CUSTOMER_ID)
	)
	TABLESPACE AJA33CORE
	LOGGING
	NOCACHE
	STORAGE (BUFFER_POOL DEFAULT);
	
CREATE TABLE TRANSACTION_GROUP3
	(
	CUSTOMERID      NUMBER (9) NOT NULL,
	AMOUNT          NUMBER (7),
	TRANSACTIONDATE TIMESTAMP,
	SOURCETYPE      VARCHAR2 (1) CHECK (sourcetype='S' OR  sourcetype='C'),
	SOURCEID        NUMBER (9),
	TARGETTYPE      VARCHAR2 (1) CHECK (targettype='S' OR  targettype='C'),
	TARGETID        NUMBER (9),
	PRIMARY KEY (CUSTOMERID),
	FOREIGN KEY (SOURCEID) REFERENCES AJA33CORE.ACCOUNT_GROUP1 (ACCOUNTID),
	FOREIGN KEY (TARGETID) REFERENCES AJA33CORE.ACCOUNT_GROUP1 (ACCOUNTID)
	)